### ISSUE TITLE
Running the default docker run doesn't work

### ISSUE THREAD

**Issue by coco98** [robertwtucker/docker-realm-object-server#5]
Running this command:
`docker run -ti -v $PWD/data:/var/lib/realm/object-server -p 9080:9080 robertwtucker/realm-object-server`

results in this:
```
read configuration from /etc/realm/configuration.yml.
Error: mmap() failed: Invalid argumentsize: 1456offset: 0
    at Error (native)
    at AuthRealmUpgrader.getSchemaVersion (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/upgrader/AuthRealmUpgrader.js:352:25)
    at AuthRealmUpgrader.run (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/upgrader/AuthRealmUpgrader.js:61:35)
    at handlers.forEach.handler (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/upgrader/UpgradeHandler.js:33:15)
    at Array.forEach (native)
    at UpgradeHandler.run (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/upgrader/UpgradeHandler.js:32:19)
    at Object.<anonymous> (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/run.js:34:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by robertwtucker** [comment]
Are you still experiencing this issue? I have tried but have not been able to reproduce this error with either the default configuration.yml or when supplying a custom one. The closest thing I've found searching is a similarly unreproducible error in Realm Core ([#2694](https://github.com/realm/realm-core/issues/2694)).
